
package com.code.api.dto;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CustomerDTO {
	private String name;
	private String emailid;
	//is is generated by its own so not needed
	//no need to share the password
}
